CREATE SCHEMA CMAC_DB
USE CMAC_DB
CREATE TABLE cmac_message (
    CMACMessageNumber INT NOT NULL,
    CMACCapIdentifier INT NOT NULL,
    CMACSender VARCHAR(180) NOT NULL,
    CMACDateTime DATE NOT NULL,
    CMACMessageType VARCHAR(165) NOT NULL,
    CONSTRAINT PK_CMACMessage PRIMARY KEY (CMACMessageNumber)
);
CREATE TABLE cmac_alert (
    CMACSenderName VARCHAR(180) NOT NULL,
    CMACAlertArea VARCHAR(200),
    CMACExpiresDateTime DATE NOT NULL
);
CREATE TABLE cmac_alert_geography (
    CMACAreaDescription VARCHAR(200) NOT NULL,
    CMACPolygon INT NOT NULL,
    CMACCirlce INT NOT NULL,
    CMACCMASGeocode INT NOT NULL
);
ALTER TABLE cmac_alert ADD CONSTRAINT FK_CMACMessageNumber FOREIGN KEY (CMACMessageNumber) REFERENCES cmac_message (CMACMessageNumber) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cmac_alert ADD CONSTRAINT FK_CMACCAPIdentifier FOREIGN KEY (CMACCapIdentifier) REFERENCES cmac_message (CMACCapIdentifier) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cmac_alert_geography ADD CONSTRAINT FK_CMACMessageNumber FOREIGN KEY (CMACMessageNumber) REFERENCES cmac_message (CMACMessageNumber) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE cmac_alert_geography ADD CONSTRAINT FK_CMACCAPIdentifier FOREIGN KEY (CMACCapIdentifier) REFERENCES cmac_message (CMACCapIdentifier) ON DELETE NO ACTION ON UPDATE NO ACTION;
